feature/ZIEL-42
wgslr/zielbruks pull request #28
Opened 2019-05-15 19:59 UTC by JuliaDutkiewicz

2019-05-15 20:46 UTC, MiRudnik commented
Nie chcemy jakoś opanować wielkości tej legendy? Bo w tej chwili u mnie mieści się łącznie 12 opisów do tych kolorów, wszystkie następne zaczynają wystawać i to dla np. D17 może być długą listą jeśli chodzi o same sale.
Druga rzecz, nie wiem czy do końca do tego taska ale trochę tak, teraz jak ktoś edytuje na nieistniejącą salę i później ją poprawi to ona zostaje w bazie i jest wyświetlana na legendzie mimo że nie ma żadnych zajęć do niej.

2019-05-15 23:39 UTC, wgslr commented
Co do uwag @MiRudnik:
IMO ciężko mówić o opanowaniu długości, bo nie można arbitralnie uciąć legendy w połowie kiedy potrzebna jest cała :P
Proponowałbym natomiast zmniejszenie wysokości linii w niej i/lub próbę wyświetlenia jej w dwóch kolumnach jeśli tylko zmieszczą się na ekranie.
Odfiltrowanie (lub usuwanie w porę z bazy) sal/grup które nie mają żadnych zajęć też będzie fajną poprawą żeby się nie rozrosła za bardzo.

2019-05-15 23:40 UTC, wgslr requested changes

2019-05-15 23:40 UTC, wgslr commented on scheduler/templates/scheduler.html
> +                        <li style="color:{{ a.1 }}; font-size: 150%;"><span style="color:black; font-size: 50%;">{{ a.0 }}</span></li>
Bardzo sprytne wykorzystanie kropki z `<li>` do kolorowania, podoba mi się :clap:

2019-05-15 23:40 UTC, wgslr commented on scheduler/templates/scheduler.html
> +                        <li style="color:{{ a.1 }}; font-size: 150%;"><span style="color:black; font-size: 50%;">{{ a.0 }}</span></li>
Ta lista wchodzi teraz za kalendarz:. 
![overflow](https://user-images.githubusercontent.com/6932414/57816185-b05b4e00-777a-11e9-88b2-c79b6e093536.png)

Obejmij proszę całą tą pętlę (i osobno drugą) elementem `<ul>` (patrz [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li)), wtedy lista będzie elementem blokowym i ustawi się ładnie obok kalendarza.

2019-05-15 23:46 UTC, MiRudnik commented
@wgslr, myślałem o ustaleniu wysokości na taką jak dla kalendarza i dodanie jakiegoś suwaka do ew. scrollowania ale whatever works :P

2019-05-15 23:49 UTC, wgslr commented
Racja, że też o suwaku nie pomyślałem. :+1:

2019-05-23 17:01 UTC, MiRudnik approved these changes

2019-05-23 17:02 UTC, merged