Feature/ziel 53
wgslr/zielbruks pull request #31
Opened 2019-05-21 11:44 UTC by PiekarzKarolina

2019-05-22 16:39 UTC, wgslr requested changes

2019-05-22 16:39 UTC, wgslr commented on scheduler/templates/editable_conflicts_list.html
> +    function toggle(source) {
Proponowałbym nazwę np. `toggleAll`, żeby było jasne że ta funckja nie dotyczy klikania checkboksów przy pojedynczych zajęciach

2019-05-23 17:03 UTC, JuliaDutkiewicz approved these changes

2019-05-23 17:14 UTC, wgslr approved these changes

2019-05-23 17:14 UTC, merged